// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_visits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT count(*)::bigint AS total
FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkVisits)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createLinkVisit = `-- name: CreateLinkVisit :execrows
INSERT INTO link_visits (link_id, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLinkVisitParams struct {
	LinkID    int64
	Ip        string
	UserAgent string
	Referer   string
	Status    int32
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (int64, error) {
	result, err := q.db.Exec(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLinkVisitsRange = `-- name: ListLinkVisitsRange :many
SELECT id, link_id, created_at, ip, user_agent, status
FROM link_visits
ORDER BY id
    LIMIT $1 OFFSET $2
`

type ListLinkVisitsRangeParams struct {
	Limit  int32
	Offset int32
}

type ListLinkVisitsRangeRow struct {
	ID        int64
	LinkID    int64
	CreatedAt pgtype.Timestamptz
	Ip        string
	UserAgent string
	Status    int32
}

func (q *Queries) ListLinkVisitsRange(ctx context.Context, arg ListLinkVisitsRangeParams) ([]ListLinkVisitsRangeRow, error) {
	rows, err := q.db.Query(ctx, listLinkVisitsRange, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkVisitsRangeRow
	for rows.Next() {
		var i ListLinkVisitsRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
