// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT count(*)::bigint AS total
FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name)
VALUES ($1, $2)
    RETURNING id, original_url, short_name
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortName   string
}

type CreateLinkRow struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortName)
	var i CreateLinkRow
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ShortName)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name
FROM links
WHERE id = $1
`

type GetLinkRow struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

func (q *Queries) GetLink(ctx context.Context, id int64) (GetLinkRow, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i GetLinkRow
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ShortName)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_name
FROM links
WHERE short_name = $1
`

type GetLinkByShortNameRow struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (GetLinkByShortNameRow, error) {
	row := q.db.QueryRow(ctx, getLinkByShortName, shortName)
	var i GetLinkByShortNameRow
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ShortName)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, short_name
FROM links
ORDER BY id
`

type ListLinksRow struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

func (q *Queries) ListLinks(ctx context.Context) ([]ListLinksRow, error) {
	rows, err := q.db.Query(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksRow
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(&i.ID, &i.OriginalUrl, &i.ShortName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksRange = `-- name: ListLinksRange :many
SELECT id, original_url, short_name
FROM links
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListLinksRangeParams struct {
	Limit  int32
	Offset int32
}

type ListLinksRangeRow struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

func (q *Queries) ListLinksRange(ctx context.Context, arg ListLinksRangeParams) ([]ListLinksRangeRow, error) {
	rows, err := q.db.Query(ctx, listLinksRange, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksRangeRow
	for rows.Next() {
		var i ListLinksRangeRow
		if err := rows.Scan(&i.ID, &i.OriginalUrl, &i.ShortName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET original_url = $2,
    short_name   = $3
WHERE id = $1
    RETURNING id, original_url, short_name
`

type UpdateLinkParams struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

type UpdateLinkRow struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error) {
	row := q.db.QueryRow(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.ShortName)
	var i UpdateLinkRow
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ShortName)
	return i, err
}
